[pytest]
# Indica a Pytest la ruta exacta hacia el archivo settings.py de tu proyecto
DJANGO_SETTINGS_MODULE = core.settings

# Opcional pero recomendado: define el patrón de nombres que Pytest buscará
python_files = tests.py test_*.py *_tests.py