# Generated by Django 5.0.14 on 2026-05-29 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('billetera_usuario', 'Billetera del usuario'), ('billetera_casa', 'Billetera de la casa'), ('apuesta_pendiente', 'Pending Bets'), ('bonus', 'Bonus')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, help_text='Null si la cuenta pertenece a la casa ', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direccion', models.CharField(choices=[('CREDITO', 'Credito (+)'), ('DEBITO', 'Debito (-)')], max_length=18)),
                ('transaccion_id', models.UUIDField(db_index=True)),
                ('id_referencia', models.UUIDField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.account')),
                ('tipo_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
    ]
